### ISSUE TITLE
Is OrbitStateVector defined in ECI or ECEF reference frame?

### ISSUE THREAD

**Issue by minecraft2048** [JuliaSpace/SatelliteToolboxBase.jl#5]
I'm trying to do some orbit analysis, and I got my state vectors in ECEF reference frame.

But the help command for `OrbitStateVector` only mentions that the position and velocity vectors are in m and m/s, they didn't mention the reference frame of these vectors:

```
help?> OrbitStateVector
search: OrbitStateVector

  struct OrbitStateVector{Tepoch<:Number, T<:Number} <: Orbit{Tepoch, T}

  Store the state vector representation of an orbit.

  Fields
  ≡≡≡≡≡≡

    •  t::Tepoch: Epoch [Julian Day].

    •  r::SVector{3, T}: Position vector [m].

    •  v::SVector{3, T}: Velocity vector [m/s].

    •  a::SVector{3, T}: Acceleration vector [m/s²].

  ────────────────────────────────────────────────────────────────────────────────────────────────────

  OrbitStateVector(t::Tepoch, r::AbstractVector{Tr}, v::AbstractVector{Tv}[, a::AbstractVector{Ta}])

  Create an orbit state vector with epoch t [Julian Day], position r [m], velocity v [m / s], and
  acceleration a [m / s²]. If the latter is omitted, it will be filled with [0, 0, 0].

  The object type is obtained by promoting Tr, Tv, and Ta.
```

Do I need to convert the ECEF state vectors to ECI, or keep it as is?

**Comment by ronisbr** [comment]
Hi @minecraft2048 !

It really depends on your application. It can be in ECI or ECEF. We have functions to convert between them: `sv_eci_to_eci`, `sv_eci_to_ecef`, and so on. The only important thing is that the velocity must be measured by an observer in that reference frame.
